[scripts/retry] Use func by sj26 which exits with cmd rc when all fail
The issue was that repo sync failed in my case so I build images which
where not in alliance with base.xml.

diff --git a/scripts/retry b/scripts/retry
--- a/scripts/retry
+++ b/scripts/retry
@@ -1,10 +1,23 @@
 #!/bin/bash
+## Credits go to Samuel `sj26` Cochran, ref: https://gist.github.com/sj26/88e1c6584397bb7c13bd11108a579746
 
-n=0
-try=$1
-cmd="${@: 2}"
-[[ $# -le 1 ]] && { echo "Usage $0 <retry_number> <Command>"; }
+set -o nounset -o pipefail -o errexit;
 
-until [[ $n -ge $try ]]; do
-    $cmd && break || { echo "Command Failed. Retry #$n"; ((n++)); sleep 1; }
+[[ $# -le 1 ]] && { echo "Usage $0 <retry_number> <command>"; }
+
+retries="${1:-}"
+shift
+
+count=0
+until "$@"; do
+    exit=$?
+    wait=$((2 ** count))
+    count=$((count + 1))
+    if [ "$count" -lt "$retries" ]; then
+        echo "Retry $count/$retries exited $exit, retrying in $wait seconds ..."
+        sleep $wait
+    else
+        echo "Retry $count/$retries exited $exit, no more retries left."
+        exit $exit
+    fi
 done
